# Standard OSIS 73-book Catholic Canon
CANON_73 = [
    {"id": 1, "code": "GEN", "name": "Genesis", "chapters": 50, "testament": "OT"},
    {"id": 2, "code": "EXO", "name": "Exodus", "chapters": 40, "testament": "OT"},
    {"id": 3, "code": "LEV", "name": "Leviticus", "chapters": 27, "testament": "OT"},
    {"id": 4, "code": "NUM", "name": "Numbers", "chapters": 36, "testament": "OT"},
    {"id": 5, "code": "DEU", "name": "Deuteronomy", "chapters": 34, "testament": "OT"},
    {"id": 6, "code": "JOS", "name": "Joshua", "chapters": 24, "testament": "OT"},
    {"id": 7, "code": "JDG", "name": "Judges", "chapters": 21, "testament": "OT"},
    {"id": 8, "code": "RUT", "name": "Ruth", "chapters": 4, "testament": "OT"},
    {"id": 9, "code": "1SA", "name": "1 Samuel", "chapters": 31, "testament": "OT"},
    {"id": 10, "code": "2SA", "name": "2 Samuel", "chapters": 24, "testament": "OT"},
    {"id": 11, "code": "1KI", "name": "1 Kings", "chapters": 22, "testament": "OT"},
    {"id": 12, "code": "2KI", "name": "2 Kings", "chapters": 25, "testament": "OT"},
    {"id": 13, "code": "1CH", "name": "1 Chronicles", "chapters": 29, "testament": "OT"},
    {"id": 14, "code": "2CH", "name": "2 Chronicles", "chapters": 36, "testament": "OT"},
    {"id": 15, "code": "EZR", "name": "Ezra", "chapters": 10, "testament": "OT"},
    {"id": 16, "code": "NEH", "name": "Nehemiah", "chapters": 13, "testament": "OT"},
    {"id": 17, "code": "TOB", "name": "Tobit", "chapters": 14, "testament": "OT"},
    {"id": 18, "code": "JDT", "name": "Judith", "chapters": 16, "testament": "OT"},
    {"id": 19, "code": "EST", "name": "Esther", "chapters": 10, "testament": "OT"},
    {"id": 20, "code": "1MA", "name": "1 Maccabees", "chapters": 16, "testament": "OT"},
    {"id": 21, "code": "2MA", "name": "2 Maccabees", "chapters": 15, "testament": "OT"},
    {"id": 22, "code": "JOB", "name": "Job", "chapters": 42, "testament": "OT"},
    {"id": 23, "code": "PSA", "name": "Psalms", "chapters": 150, "testament": "OT"},
    {"id": 24, "code": "PRO", "name": "The Proverbs", "chapters": 31, "testament": "OT"},
    {"id": 25, "code": "ECC", "name": "Ecclesiastes", "chapters": 12, "testament": "OT"},
    {"id": 26, "code": "SNG", "name": "Song of Songs", "chapters": 8, "testament": "OT"},
    {"id": 27, "code": "WIS", "name": "Wisdom", "chapters": 19, "testament": "OT"},
    {"id": 28, "code": "SIR", "name": "Sirach", "chapters": 51, "testament": "OT"},
    {"id": 29, "code": "ISA", "name": "Isaiah", "chapters": 66, "testament": "OT"},
    {"id": 30, "code": "JER", "name": "Jeremiah", "chapters": 52, "testament": "OT"},
    {"id": 31, "code": "LAM", "name": "Lamentations", "chapters": 5, "testament": "OT"},
    {"id": 32, "code": "BAR", "name": "Baruch", "chapters": 6, "testament": "OT"},
    {"id": 33, "code": "EZK", "name": "Ezekiel", "chapters": 48, "testament": "OT"},
    {"id": 34, "code": "DAN", "name": "Daniel", "chapters": 14, "testament": "OT"},
    {"id": 35, "code": "HOS", "name": "Hosea", "chapters": 14, "testament": "OT"},
    {"id": 36, "code": "JOL", "name": "Joel", "chapters": 3, "testament": "OT"},
    {"id": 37, "code": "AMO", "name": "Amos", "chapters": 9, "testament": "OT"},
    {"id": 38, "code": "OBA", "name": "Obadiah", "chapters": 1, "testament": "OT"},
    {"id": 39, "code": "JON", "name": "Jonah", "chapters": 4, "testament": "OT"},
    {"id": 40, "code": "MIC", "name": "Micah", "chapters": 7, "testament": "OT"},
    {"id": 41, "code": "NAM", "name": "Nahum", "chapters": 3, "testament": "OT"},
    {"id": 42, "code": "HAB", "name": "Habakkuk", "chapters": 3, "testament": "OT"},
    {"id": 43, "code": "ZEP", "name": "Zephaniah", "chapters": 3, "testament": "OT"},
    {"id": 44, "code": "HAG", "name": "Haggai", "chapters": 2, "testament": "OT"},
    {"id": 45, "code": "ZEC", "name": "Zechariah", "chapters": 14, "testament": "OT"},
    {"id": 46, "code": "MAL", "name": "Malachi", "chapters": 4, "testament": "OT"},
    {"id": 47, "code": "MAT", "name": "Matthew", "chapters": 28, "testament": "NT"},
    {"id": 48, "code": "MRK", "name": "Mark", "chapters": 16, "testament": "NT"},
    {"id": 49, "code": "LUK", "name": "Luke", "chapters": 24, "testament": "NT"},
    {"id": 50, "code": "JHN", "name": "John", "chapters": 21, "testament": "NT"},
    {"id": 51, "code": "ACT", "name": "Acts", "chapters": 28, "testament": "NT"},
    {"id": 52, "code": "ROM", "name": "Romans", "chapters": 16, "testament": "NT"},
    {"id": 53, "code": "1CO", "name": "1 Corinthians", "chapters": 16, "testament": "NT"},
    {"id": 54, "code": "2CO", "name": "2 Corinthians", "chapters": 13, "testament": "NT"},
    {"id": 55, "code": "GAL", "name": "Galatians", "chapters": 6, "testament": "NT"},
    {"id": 56, "code": "EPH", "name": "Ephesians", "chapters": 6, "testament": "NT"},
    {"id": 57, "code": "PHP", "name": "Philippians", "chapters": 4, "testament": "NT"},
    {"id": 58, "code": "COL", "name": "Colossians", "chapters": 4, "testament": "NT"},
    {"id": 59, "code": "1TH", "name": "1 Thessalonians", "chapters": 5, "testament": "NT"},
    {"id": 60, "code": "2TH", "name": "2 Thessalonians", "chapters": 3, "testament": "NT"},
    {"id": 61, "code": "1TI", "name": "1 Timothy", "chapters": 6, "testament": "NT"},
    {"id": 62, "code": "2TI", "name": "2 Timothy", "chapters": 4, "testament": "NT"},
    {"id": 63, "code": "TIT", "name": "Titus", "chapters": 3, "testament": "NT"},
    {"id": 64, "code": "PHM", "name": "Philemon", "chapters": 1, "testament": "NT"},
    {"id": 65, "code": "HEB", "name": "Hebrews", "chapters": 13, "testament": "NT"},
    {"id": 66, "code": "JAS", "name": "James", "chapters": 5, "testament": "NT"},
    {"id": 67, "code": "1PE", "name": "1 Peter", "chapters": 5, "testament": "NT"},
    {"id": 68, "code": "2PE", "name": "2 Peter", "chapters": 3, "testament": "NT"},
    {"id": 69, "code": "1JN", "name": "1 John", "chapters": 5, "testament": "NT"},
    {"id": 70, "code": "2JN", "name": "2 John", "chapters": 1, "testament": "NT"},
    {"id": 71, "code": "3JN", "name": "3 John", "chapters": 1, "testament": "NT"},
    {"id": 72, "code": "JUD", "name": "Jude", "chapters": 1, "testament": "NT"},
    {"id": 73, "code": "REV", "name": "Revelation", "chapters": 22, "testament": "NT"}
]

BOOK_BY_ID = {b["id"]: b for b in CANON_73}
BOOK_BY_CODE = {b["code"]: b for b in CANON_73}
