# 73-book Catholic / Interconfessional Canon for Shinkyōdōyaku (新共同訳 - vid 1819)
SHINKYO_CANON = [
    # Pentateuch
    {"code": "GEN", "name": "創世記", "chapters": 50},
    {"code": "EXO", "name": "出エジプト記", "chapters": 40},
    {"code": "LEV", "name": "レビ記", "chapters": 27},
    {"code": "NUM", "name": "民数記", "chapters": 36},
    {"code": "DEU", "name": "申命記", "chapters": 34},
    # Historical
    {"code": "JOS", "name": "ヨシュア記", "chapters": 24},
    {"code": "JDG", "name": "士師記", "chapters": 21},
    {"code": "RUT", "name": "ルツ記", "chapters": 4},
    {"code": "1SA", "name": "サムエル記上", "chapters": 31},
    {"code": "2SA", "name": "サムエル記下", "chapters": 24},
    {"code": "1KI", "name": "列王記上", "chapters": 22},
    {"code": "2KI", "name": "列王記下", "chapters": 25},
    {"code": "1CH", "name": "歴代誌上", "chapters": 29},
    {"code": "2CH", "name": "歴代誌下", "chapters": 36},
    {"code": "EZR", "name": "エズラ記", "chapters": 10},
    {"code": "NEH", "name": "ネヘミヤ記", "chapters": 13},
    {"code": "TOB", "name": "トビト記", "chapters": 14},
    {"code": "JDT", "name": "ユディト記", "chapters": 16},
    {"code": "EST", "name": "エステル記", "chapters": 10},
    {"code": "1MA", "name": "マカバイ記一", "chapters": 16},
    {"code": "2MA", "name": "マカバイ記二", "chapters": 15},
    # Wisdom / Poetry
    {"code": "JOB", "name": "ヨブ記", "chapters": 42},
    {"code": "PSA", "name": "詩編", "chapters": 150},
    {"code": "PRO", "name": "箴言", "chapters": 31},
    {"code": "ECC", "name": "コヘレトの言葉", "chapters": 12},
    {"code": "SNG", "name": "雅歌", "chapters": 8},
    {"code": "WIS", "name": "知恵の書", "chapters": 19},
    {"code": "SIR", "name": "シラ書", "chapters": 51},
    # Prophets
    {"code": "ISA", "name": "イザヤ書", "chapters": 66},
    {"code": "JER", "name": "エレミヤ書", "chapters": 52},
    {"code": "LAM", "name": "哀歌", "chapters": 5},
    {"code": "BAR", "name": "バルク書", "chapters": 6},
    {"code": "EZK", "name": "エゼキエル書", "chapters": 48},
    {"code": "DAN", "name": "ダニエル書", "chapters": 14},
    {"code": "HOS", "name": "ホセア書", "chapters": 14},
    {"code": "JOL", "name": "ヨエル書", "chapters": 4},
    {"code": "AMO", "name": "アモス書", "chapters": 9},
    {"code": "OBA", "name": "オバデヤ書", "chapters": 1},
    {"code": "JON", "name": "ヨナ書", "chapters": 4},
    {"code": "MIC", "name": "ミカ書", "chapters": 7},
    {"code": "NAM", "name": "ナホム書", "chapters": 3},
    {"code": "HAB", "name": "ハバクク書", "chapters": 3},
    {"code": "ZEP", "name": "ゼファニヤ書", "chapters": 3},
    {"code": "HAG", "name": "ハガイ書", "chapters": 2},
    {"code": "ZEC", "name": "ゼカリヤ書", "chapters": 14},
    {"code": "MAL", "name": "マラキ書", "chapters": 3},
    # New Testament - Gospels & Acts
    {"code": "MAT", "name": "マタイによる福音書", "chapters": 28},
    {"code": "MRK", "name": "マルコによる福音書", "chapters": 16},
    {"code": "LUK", "name": "ルカによる福音書", "chapters": 24},
    {"code": "JHN", "name": "ヨハネによる福音書", "chapters": 21},
    {"code": "ACT", "name": "使徒言行録", "chapters": 28},
    # Epistles
    {"code": "ROM", "name": "ローマの信徒への手紙", "chapters": 16},
    {"code": "1CO", "name": "コリントの信徒への手紙一", "chapters": 16},
    {"code": "2CO", "name": "コリントの信徒への手紙二", "chapters": 13},
    {"code": "GAL", "name": "ガラテヤの信徒への手紙", "chapters": 6},
    {"code": "EPH", "name": "エフェソの信徒への手紙", "chapters": 6},
    {"code": "PHP", "name": "フィリピの信徒への手紙", "chapters": 4},
    {"code": "COL", "name": "コロサイの信徒への手紙", "chapters": 4},
    {"code": "1TH", "name": "テサロニケの信徒への手紙一", "chapters": 5},
    {"code": "2TH", "name": "テサロニケの信徒への手紙二", "chapters": 3},
    {"code": "1TI", "name": "テモテへの手紙一", "chapters": 6},
    {"code": "2TI", "name": "テモテへの手紙二", "chapters": 4},
    {"code": "TIT", "name": "テトスへの手紙", "chapters": 3},
    {"code": "PHM", "name": "フィレモンへの手紙", "chapters": 1},
    {"code": "HEB", "name": "ヘブライ人への手紙", "chapters": 13},
    {"code": "JAS", "name": "ヤコブの手紙", "chapters": 5},
    {"code": "1PE", "name": "ペトロの手紙一", "chapters": 5},
    {"code": "2PE", "name": "ペトロの手紙二", "chapters": 3},
    {"code": "1JN", "name": "ヨハネの手紙一", "chapters": 5},
    {"code": "2JN", "name": "ヨハネの手紙二", "chapters": 1},
    {"code": "3JN", "name": "ヨハネの手紙三", "chapters": 1},
    {"code": "JUD", "name": "ユダの手紙", "chapters": 1},
    {"code": "REV", "name": "ヨハネの黙示録", "chapters": 22}
]
